### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Samm-gh** [viral32111/facepunch-commits#1]
https://npm.pkg.github.com/viral32111 is a 404 page making it so that you cannot install the package through a .npmrc file.

**Comment by viral32111** [comment]
I'm not too sure why this is happening, when I wrote the package this worked.

The [GitHub Packages documentation](https://docs.github.com/en/free-pro-team@latest/packages/guides/configuring-npm-for-use-with-github-packages#installing-a-package) still says this is the method for configuring installations from GitHub Packages.

**Comment by viral32111** [comment]
https://docs.github.com/en/packages/guides/configuring-npm-for-use-with-github-packages#installing-a-package

I suppose use `@viral32111:registry=https://npm.pkg.github.com` instead of `https://npm.pkg.github.com/viral32111` as the registry, it must've changed at some point. Should then be installable by running ` npm install @viral32111/facepunch-commits@1.1.0`.

Sorry about the huge wait, I completely forgot this issue existed.
